from typing import List

from uc_flow_schemas import flow
from uc_flow_schemas.flow import (
    Property,
    OptionValue, 
    DisplayOptions,
    )

from node.schemas.enums import (
    Properties,
    Resource, 
    Operation, 
    Association, 
    AssociationsType, 
    ContactLifecyclestage, 
    DealStage, 
    Association, 
    ObjectsAssociationsAPI,
    )


class NodeType(flow.NodeType):
    id: str = '9a427963-def2-487b-8890-0a0833270c2c'
    type: flow.NodeType.Type = flow.NodeType.Type.action
    name: str = 'example_alfacrm'
    displayName: str = 'Example alfaCRM'
    icon: str = '<svg><text x="8" y="50" font-size="50">🤖</text></svg>'
    group: List[str] = ["integration"]
    version: int = 1
    description: str = 'Example alfaCRM'
    inputs: List[str] = ['main']
    outputs: List[str] = ['main']
    credentials: List[flow.NodeType.Credential] = [
        flow.NodeType.Credential(name="alfacrm_api_auth", required=False)
    ]
    properties: List[Property] = [
        Property(
            displayName='Access token',
            name='access_token',
            type=Property.Type.STRING,
            default='',
        ),
        Property(
            displayName='Действие',
            name='resource',
            type=Property.Type.OPTIONS,
            noDataExpression=True,
            options=[
                OptionValue(
                    name='Проверка авторизации',
                    value=Resource.check_authorization,
                ),
                OptionValue(
                    name='Contact',
                    value=Resource.contact,
                ),
                OptionValue(
                    name='Deal',
                    value=Resource.deal,
                ),
                OptionValue(
                    name='Association',
                    value=Resource.association,
                ),
            ],
        ),
        Property(
            displayName='Operation',
            name='operation',
            type=Property.Type.OPTIONS,
            noDataExpression=True,
            options=[
                OptionValue(
                    name='Create',
                    value=Operation.create_association,
                    description='',
                ),
            ],
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.association, 
                    ],
                },
            ),
        ),
        Property(
            displayName='Operation',
            name='operation',
            type=Property.Type.OPTIONS,
            noDataExpression=True,
            options=[
                OptionValue(
                    name='Create',
                    value=Operation.create_contact,
                    description='',
                ),
                OptionValue(
                    name='Update',
                    value=Operation.update_contact,
                    description='',
                ),
                OptionValue(
                    name='Delete',
                    value=Operation.delate_contact,
                    description='',
                ),
            ],
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.contact, 
                    ],
                },
            ),
        ),
        Property(
            displayName='Operation',
            name='operation',
            type=Property.Type.OPTIONS,
            noDataExpression=True,
            options=[
                OptionValue(
                    name='Create',
                    value=Operation.create_deal,
                    description='',
                ),
                OptionValue(
                    name='Update',
                    value=Operation.update_deal,
                    description='',
                ),
                OptionValue(
                    name='Delete',
                    value=Operation.delate_deal,
                    description='',
                ),
                OptionValue(
                    name='Read',
                    value=Operation.read_deal,
                    description='',
                ),
            ],
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.deal, 
                    ],
                },
            ),
        ),
        Property(
            displayName='ID object',
            name='id_object',
            type=Property.Type.STRING,
            default='',
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.deal,
                        Resource.contact,
                    ],
                    'operation': [
                        Operation.update_deal,
                        Operation.delate_deal,
                        Operation.update_contact,
                        Operation.delate_contact,
                        Operation.read_deal,
                    ],
                },
            ),
        ),
        Property(
            displayName='Need create association',
            name='need_create_association',
            type=Property.Type.BOOLEAN,
            default=False,
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.deal,
                        Resource.contact,
                    ],
                    'operation': [
                        Operation.create_contact,
                        Operation.create_deal,
                    ],
                },
            ),
        ),
        Property(
            displayName='Properties',
            name='properties',
            type=Property.Type.COLLECTION,
            default={},
            placeholder='Add',
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.contact,
                    ],
                    'operation': [
                        Operation.update_contact, 
                        Operation.create_contact,
                    ],
                },
            ),
            options=[
                Property(
                    displayName='email',
                    name=Properties.contact_email,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.contact_email,
                            default='example@mail.com',
                        ),
                    ],
                ),
                Property(
                    displayName='firstname',
                    name=Properties.contact_firstname,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.contact_firstname,
                            default='Alex',
                        ),
                    ],
                ),
                Property(
                    displayName='lastname',
                    name=Properties.contact_lastname,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.contact_lastname,
                            default='Ivanov',
                        ),
                    ],
                ),
                Property(
                    displayName='phone',
                    name=Properties.contact_phone,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Properties.contact_phone,
                            default=88005553535,
                        ),
                    ],
                ),
                Property(
                    displayName='company',
                    name=Properties.contact_company,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.contact_company,
                            default='',
                        ),
                    ],
                ),
                Property(
                    displayName='website',
                    name=Properties.contact_website,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.contact_website,
                            default='https://example.com/',
                        ),
                    ],
                ),
                Property(
                    displayName='lifecyclestage',
                    name=Properties.contact_lifecyclestage,
                    noDataExpression=True,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Properties.contact_lifecyclestage,
                            options=[
                                OptionValue(
                                    name=ContactLifecyclestage.customer,
                                    value=ContactLifecyclestage.customer,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.lead,
                                    value=ContactLifecyclestage.lead,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.subscriber,
                                    value=ContactLifecyclestage.subscriber,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.marketingqualifiedlead,
                                    value=ContactLifecyclestage.marketingqualifiedlead,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.salesqualifiedlead,
                                    value=ContactLifecyclestage.salesqualifiedlead,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.opportunity,
                                    value=ContactLifecyclestage.opportunity,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.evangelist,
                                    value=ContactLifecyclestage.evangelist,
                                ),
                                OptionValue(
                                    name=ContactLifecyclestage.other,
                                    value=ContactLifecyclestage.other,
                                ),
                            ]
                        ),
                    ],
                ),
            ],
        ),
        Property(
            displayName='Properties',
            name='properties',
            type=Property.Type.COLLECTION,
            default={},
            placeholder='Add',
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.deal,
                    ],
                    'operation': [
                        Operation.update_deal, 
                        Operation.create_deal,
                    ],
                },
            ),
            options=[
                Property(
                    displayName='amount',
                    name=Properties.deal_amount,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Properties.deal_amount,
                            default=15000,
                        ),
                    ],
                ),
                Property(
                    displayName='closedate',
                    name=Properties.deal_close_date,
                    values=[
                        Property(
                            type=Property.Type.DATETIME,
                            name=Properties.deal_close_date,
                            default='',
                        ),
                    ],
                ),
                Property(
                    displayName='dealname',
                    name=Properties.deal_name,
                    values=[
                        Property(
                            type=Property.Type.STRING,
                            name=Properties.deal_name,
                            default='Example',
                        ),
                    ],
                ),
                Property(
                    displayName='pipeline',
                    name=Properties.deal_pipeline,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Properties.deal_pipeline,
                            options=[
                                OptionValue(
                                    name = 'default',
                                    value= 'default',
                                ),
                            ],
                        ),
                    ],
                ),
                Property(
                    displayName='dealstage',
                    name=Properties.deal_stage,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Properties.deal_stage,
                            options=(
                                OptionValue(
                                    name=DealStage.appointmentscheduled,
                                    value=DealStage.appointmentscheduled,
                                ),
                                OptionValue(
                                    name=DealStage.closedlost,
                                    value=DealStage.closedlost,
                                ),
                                OptionValue(
                                    name=DealStage.qualifiedtobuy,
                                    value=DealStage.qualifiedtobuy,
                                ),
                                OptionValue(
                                    name=DealStage.presentationscheduled,
                                    value=DealStage.presentationscheduled,
                                ),
                                OptionValue(
                                    name=DealStage.decisionmakerboughtin,
                                    value=DealStage.decisionmakerboughtin,
                                ),
                                OptionValue(
                                    name=DealStage.contractsent,
                                    value=DealStage.contractsent,
                                ),
                                OptionValue(
                                    name=DealStage.closedwon,
                                    value=DealStage.closedwon,
                                ),
                            )
                        ),
                    ],
                ),
            ]
        ),
        Property(
            displayName='Associations',
            name='associations',
            type=Property.Type.COLLECTION,
            default={},
            placeholder='Add',
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.deal,
                        Resource.contact,
                    ],
                    'operation': [
                        Operation.create_contact, 
                        Operation.create_deal,
                    ],
                    'need_create_association': [
                        True,
                    ],
                },
            ),
            options=[
                Property(
                    displayName='to_id',
                    name=Association.association_immediately_to_id,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Association.association_immediately_to_id,
                            default=0,
                        ),
                    ],
                ),
                Property(
                    displayName='category',
                    name=Association.association_immediately_category,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Association.association_immediately_category,
                            options=[
                                OptionValue(
                                    name='HUBSPOT_DEFINED',
                                    value='HUBSPOT_DEFINED',
                                ),
                                OptionValue(
                                    name='USER_DEFINED',
                                    value='USER_DEFINED',
                                ),
                            ],
                        ),
                    ],
                ),
                Property(
                    displayName='type',
                    name=Association.association_immediately_type_id,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Association.association_immediately_type_id,
                        ),
                    ],
                ),
            ],
        ),
        Property(
            displayName='Associations',
            name='associations',
            type=Property.Type.COLLECTION,
            placeholder='Add',
            default={},
            displayOptions=DisplayOptions(
                show={
                    'resource': [
                        Resource.association,
                    ],
                    'operation': [
                        Operation.create_association, 
                    ],
                },
            ),
            options=[
                Property(
                    displayName='Type first object',
                    name=Association.associations_first,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Association.associations_first,
                            options=[
                                OptionValue(
                                    name=ObjectsAssociationsAPI.contacts,
                                    value=ObjectsAssociationsAPI.contacts,
                                ),
                                OptionValue(
                                    name=ObjectsAssociationsAPI.deals,
                                    value=ObjectsAssociationsAPI.deals,
                                ),
                            ],
                        ),
                    ],
                ),
                Property(
                    displayName='Type second object',
                    name=Association.associations_second,
                    displayOptions=DisplayOptions(
                        show={
                            'resource': [
                                Resource.association,
                            ],
                            'operation': [
                                Operation.create_association, 
                            ],
                        },
                    ),
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Association.associations_second,
                            options=[
                                OptionValue(
                                    name=ObjectsAssociationsAPI.contacts,
                                    value=ObjectsAssociationsAPI.contacts,
                                ),
                                OptionValue(
                                    name=ObjectsAssociationsAPI.deals,
                                    value=ObjectsAssociationsAPI.deals,
                                ),
                            ],
                        ),
                    ],
                ),
                Property(
                    displayName='from_id',
                    name=Association.association_separately_from_id,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Association.association_separately_from_id,
                            default=0,
                        ),
                    ],
                ),
                Property(
                    displayName='to_id',
                    name=Association.association_separately_to_id,
                    values=[
                        Property(
                            type=Property.Type.NUMBER,
                            name=Association.association_separately_to_id,
                            default=0,
                        ),
                    ],
                ),
                Property(
                    displayName='type',
                    name=Association.association_separately_type,
                    values=[
                        Property(
                            type=Property.Type.OPTIONS,
                            name=Association.association_separately_type,
                            options=[
                                OptionValue(
                                    name=AssociationsType.deal_to_contact,
                                    value=AssociationsType.deal_to_contact,
                                ),
                                OptionValue(
                                    name=AssociationsType.contact_to_deal,
                                    value=AssociationsType.contact_to_deal,
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ]
